# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        test: [150914-full, 150914-ext]
        sampler: [dynesty_1, dynesty_2, ultranest_1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        git clone https://github.com/ahnitz/pycbc.git
        cd pycbc
        git checkout post
        pip install -r requirements.txt
        pip install -r companion.txt
        pip install ultranest
        pip install .
    - name: Running inference test
      env:
        TEST: ${{matrix.test}}
        SAMPLER: ${{matrix.sampler}}
      run: |
        bash test.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.test}}_${{matrix.sampler}}
        path: ${{matrix.test}}_${{matrix.sampler}}.png
